### ISSUE TITLE
UDP should not send DLE/STX

### ISSUE THREAD

**Issue by Haavard15** [NoahCallaway/tsl-umd-v5#1]
Amateur coder here, but I think per protocol documentation the UDP sender should not have DLE/STX:

https://tslproducts.com/media/1959/tsl-umd-protocol.pdf

Page 6:

"Physical Layer
Packets are sent via UDP. Maximum packet length is 2048 bytes.
Optionally, the protocol can operate over TCP/IP, or any other byte stream interface, with the
following wrapper scheme:
DLE is defined as 0xFE
STX is defined as 0x02
Packet start is delimited by the sequence DLE/STX.
Any occurrence of the DLE character in the packet is byte stuffed to DLE/DLE.
Any byte count fields in the packet are not affected by the byte stuffing."

**Comment by NoahCallaway** [comment]
It's an interesting point you raise... There seems to be a few different interpretations of the protocol spec.

[TallyView](https://github.com/roddypratt/tallyview), for example, requires the DLE/STX sequence for a UDP UMD5.0 messages to be processed. 

When I originally wrote this implementation I tested with Sony hdcu3100's which seemed to work fine without the sequence. [This](https://github.com/josephdadams/TallyArbiter/issues/255) issue seems to need the sequence for UDP.

What hardware/software are you testing with?

I think making the sequence optional will cover all bases.

**Comment by Haavard15** [comment]
Working with a Plura PBM-224-4K

They sent me this testing application that worked, and I used Wireshark to compare the two sent data packets:
https://drive.google.com/drive/folders/1Uj4I98-qXtNg3OGV1X-JTa7NOMAoV4fm

Removing the DLE/STX made it work

```
//Add DLE/STX and stuffing
let packetBuf = new Buffer.alloc(0)
for(let i = 0; i < bufUMD.length; i++) {
    {
        packetBuf = Buffer.concat([packetBuf, Buffer.from([bufUMD[i]])])
    }
}
return packetBuf
```


I am going to try TSL v5 directly with our Panasonic UE150 for fun now that they support it via a firmware update

Also, big thanks for the library regardless, here is our working setup :-)
https://drive.google.com/file/d/1AuD2aXmZrUCbiCjI6-goHEweZbfViIdY/view

**Comment by NoahCallaway** [comment]
Awesome! Great to see it working in your setup too. 
Thanks for your feedback and willingness to test!!

I'll update the module so DLE/STX is off by default for UDP and on for TCP.
I'll also include and option to override this and force the sequence on/off.

**Comment by NoahCallaway** [comment]
Changes made.
Let me know if your testing highlights any other issues.
