### ISSUE TITLE
Simple Tally Data to TallyArbiter

### ISSUE THREAD

**Issue by ben-bole** [NoahCallaway/tsl-umd-v5#2]
Hey there,
I am currently preparing a charity concert live stream for which I need at least one tally light.
I don't need anything fancy, so my plan was to use TallyArbiter and your node library and adapt your example script to my needs.
Basically I just need two scripts: The first one turns the tally light green and the other one turns it red.
These scripts are then triggered manually via a StreamDeck, because I have a very unpopular video mixer (RGBLink mini+) with no expansion/ scripting component.

My first draft of the script is the following:

```
const TSL5 = require('tsl-umd-v5')

var umd = new TSL5()

tally = {
    "screen": 1,
    "index": 1
}

//umd.sendTallyUDP('127.0.0.1', 8900, tally, true)

umd.sendTallyTCP('127.0.0.1', 9000, tally, true)
```

Is that possible? How do I have to configure TallyArbiter? At the moment it doesn't work as planned...

Thanks in advance, Benedict

**Comment by NoahCallaway** [comment]
Hiya,

If it fits your use case, you can use the latest version of [Bitfocus Companion](https://github.com/bitfocus/companion/releases/tag/v2.2.0) to send TSLv5 tallies from the stream deck. That might save you needing a custom script. Make sure that DLE/STX sequence option is disabled if you're sending to TallyArbiter.

If you do need to use the script then you'll need to send some tally data. The tally object needs some "ON" values. See example below.

```javascript
tally = {
    "screen": 0,
    "index": 1,
    "display": {
        "rh_tally": 1,
        "text_tally": 1,
        "lh_tally": 1,
        "brightness": 3,
        "text": "Test Tally"
    }
}

umd.sendTallyTCP('127.0.0.1', 9000, tally, false)

// Or something like 
//umd.sendTallyUDP('127.0.0.1', 8900, tally, false)
```

**Comment by ben-bole** [comment]
> Hiya,
> 
> 
> 
> If it fits your use case, you can use the latest version of [Bitfocus Companion](https://github.com/bitfocus/companion/releases/tag/v2.2.0) to send TSLv5 tallies from the stream deck. That might save you needing a custom script. Make sure that DLE/STX sequence option is disabled if you're sending to TallyArbiter.
> 
> 
> 
> If you do need to use the script then you'll need to send some tally data. The tally object needs some "ON" values. See example below.
> 
> 
> 
> ```javascript
> 
> tally = {
> 
>     "screen": 0,
> 
>     "index": 1,
> 
>     "display": {
> 
>         "rh_tally": 1,
> 
>         "text_tally": 1,
> 
>         "lh_tally": 1,
> 
>         "brightness": 3,
> 
>         "text": "Test Tally"
> 
>     }
> 
> }
> 
> 
> 
> umd.sendTallyTCP('127.0.0.1', 9000, tally, false)
> 
> 
> 
> // Or something like 
> 
> //umd.sendTallyUDP('127.0.0.1', 8900, tally, false)
> 
> ```
> 
> 
> 
> 
> 
> 

Hey,
thank you so much for the great tip! I just didn't figured out how to send the TSL calls but now it works 😃
