### ISSUE TITLE
Is there a c / c++ stack avaible? 

### ISSUE THREAD

**Issue by martinmmi** [NoahCallaway/tsl-umd-v5#3]
Hello, I programming a wireless tally via esp32. Is your java tsl-umd lib also avaible in c/c++? Or do you think i can implement it?

**Comment by NoahCallaway** [comment]
Hi @martinmmi 
Unfortunately I'm not aware of an implementations in C.
The protocol spec I used is [here](https://tslproducts.com/media/1959/tsl-umd-protocol.pdf)
